### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by johann-tam** [DIT112-V20/group-07#86]
### Description
Adding Continuous integration to the repository

### Acceptance Criteria
CI is set up to check the code both for code commits and pull requests for the Arduino sketches and Android application

**Comment by johann-tam** [comment]
Since we didn't expect this feature to take us that long we didn't create an issue for it in the first place and therefore did not reference our commits to this issue.

@mikaelhoije has been working on this issue whole week 19 & 20 while @johann-tam helped out half of week 20

**Comment by platisd** [comment]
Don't forget the most important thing which is about linking it to code/commits/pull request
