### ISSUE TITLE
Location of delivery address for the driver

### ISSUE THREAD

**Issue by johann-tam** [DIT112-V20/group-07#94]
### Description
As a driver, I want to be able to see the delivery adress provided by the user so that I can drive to that lcoation.

### Acceptance criteria
When the end user chooses a delivery adress, it should also be visible on the map for the driver.

**Comment by mikaelhoije** [comment]
We didn't implement this because we didn't have the time before our deadline and therefore we are closing it

**Comment by platisd** [comment]
You can always leave the unfinished issues open for future developers. :)
